[build]
command = "npm run build"
functions = "src/functions/"
publish = "build"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type: application/json"
    Access-Control-Allow-Methods = "GET, POST"