name: PR Workflow- Elastuc Fu-Finder
on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]
jobs:   
  build_and_test:
    env:
      NODE_ENV: development
      ELASTIC_CLOUD_ID: ${{ secrets.ELASTIC_CLOUD_ID }}
      ELASTIC_API_KEY: ${{ secrets.ELASTIC_API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm install saas & npm run build
      - run: npm run test