name: PR Workflow- Elastic Synthetics With Svelte Replicator
on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]
jobs:   
  build_e2e:
    env:
      NODE_ENV: development
      ELASTIC_CLOUD_ID: ${{ secrets.ELASTIC_CLOUD_ID }}
      ELASTIC_API_KEY: ${{ secrets.ELASTIC_API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: echo $ELASTIC_CLOUD_ID
      - run: npm install
      - run: npx nx serve elastic-fu-finder-server &
      - run: npx nx run elastic-fu-finder-e2e:e2e
  test:
    env:
      NODE_ENV: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npx nx test --project elastic-fu-finder